name: Template Node Workflow

on:
  push:
    branches:
      - main  # Adjust as necessary

jobs:
  node-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install

      - name: Build Node.js code
        run: npm run build

      - name: List directories after build
        run: ls -lah
